apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: incident-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: alb       # or nginx, etc.
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: incident-frontend-service
                port:
                  number: 80
